language: php

php:
    - 7.2
    - 7.3

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml -spn --encoding=utf-8 src/ --report-width=150
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  fast_finish: true


notifications:
    on_success: never
    on_failure: always
